community:
  enabled: true

monitoringPasscode: passcode



postgresql:
  enabled: true
  auth:
    postgresPassword: postgres
    username: sonar
    password: sonar
    database: sonarqube

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    # Standard NGINX annotations that should work in most environments
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    # Instead of configuration-snippet, use these annotations
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # This annotation handles forwarding protocol information
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/x-forwarded-for-header-name: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/x-forwarded-proto-header-name: "X-Forwarded-Proto"
    nginx.ingress.kubernetes.io/x-forwarded-host-header-name: "X-Forwarded-Host"
    nginx.ingress.kubernetes.io/x-forwarded-port-header-name: "X-Forwarded-Port"
  hosts:
    - name: sonarqube.local
      path: /