# postgres-values.yaml
global:
  postgresql:
    auth:
      username: sonar
      password: sonarPass
      database: sonar
      postgresPassword: postgresPass

primary:
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 8Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

readReplicas:
  persistence:
    storageClass: "longhorn"

volumePermissions:
  enabled: true