services:
  app:
    image: jenkins/jenkins:lts
    user: root
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: any
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: admin
    networks:
      - jenkins-net
      - proxy

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: overlay
    name: jenkins-net
  proxy:
    external: true
    name: proxy