# jenkins-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins-system
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: jenkins-system
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token