version: "3.9"

services:
  app:
    image: sonatype/nexus3:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
        reservations:
          cpus: "1.0"
          memory: 1G
    ports:
      - "8081:8081"  # Nexus Web UI
      - "8082:8082"  # Docker registry (if enabled)
    volumes:
      - nexus-data:/nexus-data
    networks:
      - nexus-net
      - proxy
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx2g -XX:MaxDirectMemorySize=2g  # Removed the UseCGroupMemoryLimitForHeap

volumes:
  nexus-data:

networks:
  nexus-net:
    driver: overlay
    name: nexus-net
  proxy:
    external: true
