# Disable built-in ingress - we'll use separate manifest
ingress:
  enabled: false

# Disable API ingress as well
apiIngress:
  enabled: false

# Production-ready authentication
auth:
  rootUser: admin
  # Use a strong password or existing secret
  rootPassword: "minioadminpassword123!"  # Change this to a strong password
  existingSecret: ""
  forcePassword: true
  usePasswordFiles: true

# Production resource limits
resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi

# Enable persistence for production
persistence:
  enabled: true
  storageClass: ""  
  size: 30Gi     
  accessModes:
    - ReadWriteOnce

# Security settings
podSecurityContext:
  enabled: true
  fsGroup: 1001
  fsGroupChangePolicy: "OnRootMismatch"

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"

# Enable network policies for security
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true

# Production probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Pod disruption budget for high availability
pdb:
  create: true
  maxUnavailable: 1

# Service account
serviceAccount:
  create: true
  automountServiceAccountToken: false

# Metrics for monitoring (optional)
metrics:
  enabled: true
  prometheusAuthType: public