hostname: kubernetes.marouanedbibih.studio

addLocal: "true"
debug: false
agentTLSMode: "strict"

replicas: 1
priorityClassName: rancher-critical

rancherImage: rancher/rancher
# rancherImageTag: v2.8.3

tls: external
systemDefaultRegistry: ""

additionalTrustedCAs: false
antiAffinity: preferred
topologyKey: kubernetes.io/hostname

auditLog:
  destination: sidecar
  hostPath: /var/log/rancher/audit/
  level: 1
  maxAge: 3
  maxBackup: 2
  maxSize: 100
  resources: {}
  image:
    repository: "rancher/mirrored-bci-micro"
    tag: 15.6.24.2
    pullPolicy: "IfNotPresent"

bootstrapPassword: Marouane@2001

# Disable ingress
ingress:
  enabled: false

service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
  annotations: {}
  labels: {}
  loadBalancerSourceRanges: []

letsEncrypt:
  enabled: false

privateCA: false
noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local

resources:
  limits:
    cpu: 1
    memory: 3Gi
  requests:
    cpu: 250m
    memory: 1Gi

imagePullSecrets: []

customLogos:
  enabled: false
  volumeKind: persistentVolumeClaim
  accessMode: ReadWriteOnce
  size: 1Gi

postDelete:
  enabled: true
  image:
    repository: rancher/shell
    tag: v0.4.0
  namespaceList:
    - cattle-fleet-system
    - cattle-system
    - rancher-operator-system
  timeout: 120
  ignoreTimeoutError: false

startupProbe:
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 12

livenessProbe:
  timeoutSeconds: 5
  periodSeconds: 30
  failureThreshold: 5

readinessProbe:
  timeoutSeconds: 5
  periodSeconds: 30
  failureThreshold: 5

certmanager:
  version: ""

extraTolerations: {}
extraNodeSelectorTerms: {}

webhook: ""
fleet: ""
extraObjects: []
