global:
  defaultStorageClass: longhorn

jenkinsUser: admin
jenkinsPassword: adminpassword

plugins:
  - git
  - workflow-aggregator
  - kubernetes
  - configuration-as-code

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 8Gi

service:
  type: ClusterIP
  ports:
    http: 8080
    https: 8443

livenessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  privileged: false

podSecurityContext:
  enabled: true
  fsGroup: 1001

resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 2000m
    memory: 4Gi

updateStrategy:
  type: RollingUpdate

networkPolicy:
  enabled: true
  allowExternal: true

ingress:
  enabled: false

extraVolumes:
  - name: empty-init-dir
    emptyDir: {}

extraVolumeMounts:
  - name: empty-init-dir
    mountPath: /docker-entrypoint-initdb.d
